### ISSUE TITLE
module:release broken

### ISSUE THREAD

**Issue by deric** [voxpupuli/puppet-blacksmith#77] opened 2019-11-05 12:47 UTC
Due to incorrect tasks order, blacksmith attempts to upload bumped (non-existing release) instead of the release that is supposed to release.
```
$ rake module:release
Cleaning for module build
Module built: /home/deric/dev/puppet/sysctl_conf/pkg/deric-sysctl_conf-0.1.0.tar.gz
Bumping version from 0.1.0 to 0.1.1
Uploading to Puppet Forge deric/sysctl_conf
rake aborted!
Errno::ENOENT: No such file or directory - File not found in /home/deric/dev/puppet/sysctl_conf/pkg with regex (?-mix:^deric-sysctl_conf-0\.1\.1\.tar\.gz$)
/home/deric/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
/home/deric/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
Tasks: TOP => module:release => module:push
(See full trace by running task with --trace)
```

**Comment by ekohl** [comment] 2020-04-23 17:11
Duplicate of https://github.com/voxpupuli/puppet-blacksmith/issues/57

**Closed by ekohl** 2020-04-23 17:11 UTC
